# GKE does not allow ReadWriteMany directly to its persistent disk
# NFS servers serve this purpose within the cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-media-server

spec:
  template:
    metadata:
      labels:
        role: nfs-media-server

    spec:
      containers:
        - name: nfs-media-server
          image: gcr.io/google_containers/volume-nfs:0.8
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /exports
              name: nfs-media-server-pvc

      volumes:
        - name: nfs-media-server-pvc
          # created upfront
          gcePersistentDisk:
            pdName: gce-nfs-disk-mediafiles
            fsType: ext4

  replicas: 1

  selector:
    matchLabels:
      role: nfs-media-server