apiVersion: v1
kind: Service
metadata:
  name: angular-nodeport-service

spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80

  selector:
    app: swagger-whats-new
    tier: frontend
    type: angular-app 