# for GKE's ingress loadbalancer
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service

spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80

  selector:
    app: swagger-whats-new
    tier: backend
    type: reverse-proxy