apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-persistent-volume-claim
  labels:
    app: swagger-whats-new
    name: media-persistent-volume-claim

spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""

  resources:
    requests:
      storage: 10Gi

  selector:
    matchLabels:
      app: swagger-whats-new
      name: media-persistent-volume