apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-volume-claim
  labels:
    app: swagger-whats-new
    name: postgres-persistent-volume-claim

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "db"

  resources:
    requests:
      storage: 10Gi