apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: db
provisioner: kubernetes.io/gce-pd

# defaul GKE's storage class has a reclaimPolicy of 'Delete'
reclaimPolicy: Retain
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none