apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  labels:
    app: swagger-whats-new

data:
  POSTGRES_USER: "swagger_whats_new"
  POSTGRES_DB: "swagger_whats_new"
  PGDATA: "/var/lib/postgresql/data/pgdata"